errorlog.settings:
  type: config_object
  label: 'Error logging for each severity level.'
  mapping:
    errorlog_0:
      type: boolean
      label: 'Severity: Emergency'
    errorlog_1:
      type: boolean
      label: 'Severity: Alert'
    errorlog_2:
      type: boolean
      label: 'Severity: Critical'
    errorlog_3:
      type: boolean
      label: 'Severity: Error'
    errorlog_4:
      type: boolean
      label: 'Severity: Warning'
    errorlog_5:
      type: boolean
      label: 'Severity: Notice'
    errorlog_6:
      type: boolean
      label: 'Severity: Info'
    errorlog_7:
      type: boolean
      label: 'Severity: Debug'
