<?php

/**
 * @file
 * Drupal Module: Web Server Logging and Alerts
 *
 * Sends logs and alerts to the web server's log.
 *
 * @Author: Khalid Baheyeldin http://2bits.com (version 6.x)
 * @Author: Maciej Zgadzaj http://zgadzaj.com (version 7.x)
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Logger\RfcLogLevel;

/**
 * Implements hook_help().
 */
function errorlog_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.errorlog':
      return '<p>' . t('Sends logs and alerts to the web server\'s error log.') . '</p>';
  }
}

/**
 * Implements hook_theme().
 */
function errorlog_theme() {
  return array(
    'errorlog_format' => array(
      'arguments' => array('log_msg' => NULL),
    ),
  );
}

/**
 * Themes error log message.
 */
function theme_errorlog_format($log_msg = array()) {
  global $base_root;
  $config = \Drupal::config('system.site');

  $severity_list = RfcLogLevel::getLevels();
  $message  = $config->get('name') ?: 'Drupal';
  $message .= '|' . $base_root;
  $message .= '|severity=' . $severity_list[$log_msg['severity']];
  $message .= '|type=' . $log_msg['type'];
  $message .= '|ip=' . $log_msg['ip'];
  $message .= '|uri=' . $log_msg['request_uri'];
  $message .= '|referer=' . $log_msg['referer'];
  $message .= '|uid=' . $log_msg['user']->uid;
  $message .= '|link=' . strip_tags($log_msg['link']);
  $message .= '|message=' . strip_tags(t($log_msg['message'], $log_msg['variables']));
  return $message;
}
